### ISSUE TITLE
Basecalling

### ISSUE THREAD

**Issue by fritzsedlazeck** [nanopore-wgs-consortium/NA12878#10]
Hi, 
I was wondering what base caller you used for the reads? I heard that there is an improvement (scrappy) or so that works better on homopolymers. Is there a plan to redo the base calling for the whole genome? 
Thanks
Fritz

**Comment by mattloose** [comment]
The whole data set has been called with metrichor currently. Chromosome 20 has a number of different base callers applied and the data for that is available in the repository. Additional analysis and base callers will be coming for the whole genome.

**Comment by nickloman** [comment]
Yes, entire dataset called with scrappie incoming. Currently scrappie and nanonet available for chr20.

**Comment by yk-tanigawa** [comment]
Hi, 

Is there any possibility that you could kindly provide `FASTA` file for chr20 base called by Metrichor for a comparison of that by Scrappie?
I could download all the fastq files and filter by chromosome, but if you have a fastq file for chr20, that would be fantastic. Thanks.

**Comment by nickloman** [comment]
Links to chr20 scrappie basecalls are now available via the README page.
