### ISSUE TITLE
Cannot Download Samples of Rel6 DNA Data

### ISSUE THREAD

**Issue by hkarakurt8742** [nanopore-wgs-consortium/NA12878#105]
Hello,
I wanted to download the FASTQ files of DNA data for performance testing of a variant calling pipeline but I cannot download the data. I tried to use http download but the download did not start (download works with RNA data) and used AWS download with the code below:
aws s3 cp s3://nanopore-human-wgs/rel6/FASTQTars/FAB39075-4246400039_Multi.tar .
And I have the error message:
fatal error: Unable to locate credentials

Also, I want to compare my VCF with reference VCF. Can I use the HG001 reference VCF from GIAB GitHub page or should I used another reference VCF.

Thank you in advance.

**Comment by mattloose** [comment]
The error is due to you not having correctly registered your aws client credentials - I have just been able to download the file you specify correctly.

You can use whichever reference VCF you wish for comparison.
