### ISSUE TITLE
ultra long reads 

### ISSUE THREAD

**Issue by jo-mc** [nanopore-wgs-consortium/NA12878#107]
I would like to get the fastq for the additional 5× coverage of the ultra-long reads only. I don't seem to be able to find any identifiers for it. Would you have the reference numbers or file list? (paper: Nanopore sequencing and assembly of a human genome with ultra-long reads, 2018) maybe too old? If not could you point  me to another similar data set, human ultra long up to about 10X, 
thanks, Joe.

**Comment by mattloose** [comment]
Hi,

The data can be found by looking at the table in release 6 here - https://github.com/nanopore-wgs-consortium/NA12878/blob/master/Genome.md#rel6-data

Thanks

Matt
