### ISSUE TITLE
Format of FAST5 files in rel6

### ISSUE THREAD

**Issue by MaxNacemit** [nanopore-wgs-consortium/NA12878#111]
I need nanopore sequencing data to train a neural network. Do the FAST5 files in the rel6 version of the dataset provide the basecalled sequence in FASTQ format as an analysis? If not, how can I get both the raw nanopore sequencing data and the sequence in FASTQ format?

**Comment by mattloose** [comment]
Hi. Sorry - I saw that this has been closed. You can download the fast5 and the fastq and pair using read ID. The fast5 files themselves do not contain fastq data.
