### ISSUE TITLE
Basecalls on latest super accuracy models

### ISSUE THREAD

**Issue by hasindu2008** [nanopore-wgs-consortium/NA12878#113]
Are there any plans to include basecalls using these latest super accuracy models now coming with Guppy/Bonito/Dorado?

**Comment by mattloose** [comment]
Yes - this is in progress and the base calls will be available shortly.

**Comment by hasindu2008** [comment]
Thanks. Out of curiosity. How are these rebasecalls done? Is it done on the AWS cloud by mounting using s3fs-fuse or do you do it locally and upload?

**Comment by hasindu2008** [comment]
@mattloose I have successfully basecalled the whole DNA dataset in the sup model. I could share if you are interested.

**Comment by mattloose** [comment]
This is already done - I believe @mitenjain is in the process of making it available.
