### ISSUE TITLE
Difficulties in finding NA12878 ONT data

### ISSUE THREAD

**Issue by weishwu** [nanopore-wgs-consortium/NA12878#117]
I think it's just me being the silly guy because I'm not seeing other posts complaining about this, but I find it so hard to find the links to download NA12787 ONT data. First, the amazon a3 link in the README (http://s3.amazon.com/nanopore-human-wgs/) does not work. I also registered an aws account and searched for "nanopore-human-wgs" but didn't get anything. I finally found a link that works for me:
https://nanopore-human-wgs.s3.amazonaws.com/index.html

Then it looks like a mess there to me. I suppose I should get NA12878 data from the "na12878" folder? But then under that folder it's another bunch of folders & files without clear names telling what they are. I need to get the fast5 files so I got into a folder whose name says "r10_fast5_by_flowcell_tar". Then it's a folder "Notts" (whatever it means). Then under "Notts" there are a set of "_Fastq.tar.gz" files. They are not fast5...

Is there a handy list of NA12878 ONT datasets with working links somewhere online? Or I just simply need to get the data that was used by [this paper](https://elifesciences.org/articles/77898#s4). The paper says "Raw and base-called nanopore data for NA12878 were obtained from rel6 nanopore WGS consortium". So where can I download this "rel6" NA12878 ONT data (fast5 and fastq)?

Thanks.

**Comment by mattloose** [comment]
Hi

did you follow the link in the readme file?

All the information is within the links there. 

Please see https://github.com/nanopore-wgs-consortium/NA12878/blob/master/Genome.md for the descriptions of the various releases.

**Comment by weishwu** [comment]
OK. Thanks!
I was confused by something when I first read the Genome.md, but clearly this is what I need. Sorry for overlooking things under the nose!
