### ISSUE TITLE
Packing bug in chromosone Y

### ISSUE THREAD

**Issue by nmiculinic** [nanopore-wgs-consortium/NA12878#13]
I've downloaded chromosome Y reads, part 1 (and only part) from the readme. 

After untaring I have folder rel3/${chr}/${fn} which smells like unresolved environment variables, that is bug in generating script. Can I still trust the data obtained?

**Comment by nickloman** [comment]
Sorry about the inconvenience! Yes, this was a problem with our tar regexp transform command, but the data will be fine. We'll try and fix this in rel5.

**Comment by nmiculinic** [comment]
Thank you!
