### ISSUE TITLE
Is there an order in the fast5 zipped files in each chromosome?

### ISSUE THREAD

**Issue by danarte** [nanopore-wgs-consortium/NA12878#20]
Hello,
The readme file states "Each complete 'part' contains 100,000 reads and should be roughly in sort order along the chromosome..."
Does that mean that the reads in each part are sorted? and each part contains reads aligning to the whole chromosome?

For example there are 9 parts of zipped fast5 files for chrom1.
Are the files in part 1 aligning to one end of the chromosome and files in part9 align to the other end? 
Or both parts have reads from all over the chromosome but in each part - reads at the beginning are aligned to the start of the chromosome while reads at the end align to the end of the chromosome?

Thanks.

**Comment by nickloman** [comment]
"Are the files in part 1 aligning to one end of the chromosome and files in part9 align to the other end?" <- yes, this one.

**Comment by danarte** [comment]
Oh, that's a problem for us.
We wanted to take a small subset of reads and we assumed each part had mixed reads from the whole chromosome.
Is there any way to get a few reads from each chromosome? (~50K reads) without downloading tens of terabytes of data?

**Comment by danarte** [comment]
We found a way to download only a few reads from each part without downloading the whole file with this command:
curl http://s3.amazonaws.com/nanopore-human-wgs/rel3-fast5-chr17.part02.tar | tar xv --strip-components=3 -C fast5Reads/chr$chr/part$part/ | head -5000

Hope that helps others.
