### ISSUE TITLE
RNAtotal?

### ISSUE THREAD

**Issue by CBlugeon** [nanopore-wgs-consortium/NA12878#21]
Have you tried to do the direct RNA protocole with total RNA as input?
And if it's possible , how much input total RNA have you used?

**Comment by nickloman** [comment]
We haven't, but it should be possible. The standard protocol uses a poly-dT adaptor so you will only sequence messenger RNA, and you will need to scale up the input according to your estimate of the amount of poly-A RNA in your sample (aiming for 500ng).

If you are interested in sequencing other RNAs you will need to design your own sequencing adaptor, see Smith et al. bioRxiv for more details  (https://www.biorxiv.org/content/early/2017/04/29/132274)
