### ISSUE TITLE
RNA read lengths

### ISSUE THREAD

**Issue by laraib85** [nanopore-wgs-consortium/NA12878#22]
Hi,

Thank you for this great resource! I was playing around with the data and trying to get an idea about the alignment properties etc. In particular I was looking at this alignment file: http://s3.amazonaws.com/nanopore-human-wgs/rna/bamFiles/NA12878-DirectRNA.pass.dedup.NoU.fastq.hg38.minimap2.sorted.bam

Correct me if I'm wrong, but the left plot on Slide 17 (on read lengths) should correspond to this dataset? However, using pysam to parse the dataset, I was only able to see ~50,000 reads longer than 5,000 bases. Am I mixing the cDNA and RNA datasets somehow? Will be grateful for further guidance on this. Thank you.

**Comment by nickloman** [comment]
I think that's expected: slide 17 X-axis starts at 5000 to demonstrate the long reads in the direct RNA dataset, but there are many shorter reads (the mean average for both datasets is around 1kb).
