### ISSUE TITLE
chr22 missing from the FAST5 files?

### ISSUE THREAD

**Issue by danarte** [nanopore-wgs-consortium/NA12878#23]
Hi,
Where is chr22 in the fast5 section?

**Comment by nickloman** [comment]
Sorry for the delay!
Hum, the links are missing from the document, but here are the direct links until I get chance to fix it:
http://s3.amazonaws.com/nanopore-human-wgs/rel3-fast5-chr22.part01.tar
http://s3.amazonaws.com/nanopore-human-wgs/rel3-fast5-chr22.part02.tar
http://s3.amazonaws.com/nanopore-human-wgs/rel3-fast5-chr22.part03.tar

**Comment by danarte** [comment]
Great, I will use it.

Thanks.
