### ISSUE TITLE
Rel4 bam files?

### ISSUE THREAD

**Issue by rdmorin** [nanopore-wgs-consortium/NA12878#25]
Are the reads from Rel4 available as bam files?

**Comment by nickloman** [comment]
We've recently re-basecalled all of rel3+rel4 with the latest version of the nanopore basecallers and named this release 'rel5'.

Minimap2 alignments as BAM files are available for this set: you might find this the most productive set of files to get started with a new analysis on, available at:

https://github.com/nanopore-wgs-consortium/NA12878/blob/master/rel5.md

Let me know if that's not what you need!
