### ISSUE TITLE
rel4 fastq files

### ISSUE THREAD

**Issue by jzook** [nanopore-wgs-consortium/NA12878#29]
There are links to the rel3 fastq files on the GitHub site, but I don't see the rel4 fastq files.  Would it be possible to add these links as well?

Thanks!
Justin

**Comment by nickloman** [comment]
They are there, but you might need to scroll the table to the right to see the DL links!

BTW rel5 is also now available (entire dataset recalled with latest Guppy).
https://github.com/nanopore-wgs-consortium/NA12878/blob/master/rel5.md
