### ISSUE TITLE
Add bam index files

### ISSUE THREAD

**Issue by kyleabeauchamp** [nanopore-wgs-consortium/NA12878#4]
I can't load the BAM urls in IGV because of missing index files

**Comment by kyleabeauchamp** [comment]
See also discussion in #3

**Comment by drchriscole** [comment]
Not working here either.

Would save a lot of downloading if ppl could just link to the BAMs directly.

**Comment by nickloman** [comment]
I didn't put the indices up because figured it was fast to just run samtools on them. But I can do!

Don't know what you mean @drchriscole ?

**Comment by drchriscole** [comment]
I mean being able to access aligned BAMs directly from URLs is particularly useful when loading data in genome browsers (e.g. IGB, Ensembl). The browsers require an index in order for it to work.

Alternative is to download all the BAMs locally and then index. Inefficient IMO.

**Comment by nickloman** [comment]
Good call, I'm doing the alignments for rel3 - when that's done I'll update with the BAM and BAI and also a merged one that you can stream from IGV etc.

**Comment by drchriscole** [comment]
Great! Looking forward to it.

**Comment by nickloman** [comment]
BAM/BAI posted for both individual flowcells and individual chromsoeomes, enjoy!
