### ISSUE TITLE
Read to Flowcell mapping

### ISSUE THREAD

**Issue by knightjimr** [nanopore-wgs-consortium/NA12878#48]
With the combined, updated Guppy calls of the full dataset, is there a way to separate the reads by flowcell?  I'd like to use actual per-flowcell dataset to evaluate the nanopore data.  The fastq file does contain "runid" values, but when I tried to separate the rel5 Guppy fastq file by runid, I'm finding at least over one thousand different run id values.  And, I can't find any place where the flowcell ID is shown in these calls.

What is the best way to access the per-flowcell basecalls for the data (is there something better than downloading the Albacore calls, building the mapping of readId to flowcell, then splitting the Guppy calls that way)?

**Comment by nickloman** [comment]
The Guppy stuff got called en masse and sadly the flowcell ID is not recorded in the FASTQ header. So yeah you'd probably have to match it up with the rel3/rel4 flowcell FASTQs by header ID (https://github.com/nanopore-wgs-consortium/NA12878/blob/master/nanopore-human-genome/rel_3_4.md). I think we're going to re-basecall these reads soon ('rel6') so I might look into how we can include the flowcell ID in the FASTQ header.

**Comment by nickloman** [comment]
@mattloose has just reminded me that we have this information in the sqlite poredb. I'll export a runid->flowcell lookup for you!

**Comment by nickloman** [comment]
Hi again,

Please use this lookup - hope it is helpful
https://github.com/nanopore-wgs-consortium/NA12878/blob/master/nanopore-human-genome/flowcells_vs_runid.txt

Nick
