### ISSUE TITLE
throughput variability

### ISSUE THREAD

**Issue by dwaggott** [nanopore-wgs-consortium/NA12878#5]
Awesome!

I'd be very interested in any observations on what's contributing to the GB variability. Looking forward to more information as the project matures. New to the game, but quite a few minIONs in proximity and a promethION is being patiently waited for.

Daryl

**Comment by nickloman** [comment]
The $64,000 question! One thing I can say that might be helpful is that some of the paired runs done in Birmingham or Nottingham on or around the same time were from the exact same library preparation, so some of the variability seen is most likely to be flowcell related.

**Comment by dwaggott** [comment]
Thanks!
