### ISSUE TITLE
FAST5 missing

### ISSUE THREAD

**Issue by eleniadam** [nanopore-wgs-consortium/NA12878#57]
Hello @mitenjain ,

In order to use the nanopore reads on my research, I have been looking for the .FAST5 files (raw) of rel4 (ultra read set) of the NA12878 cell line. But I have been unable to locate them.
Are they available somewhere else? 

Is there a possibility that maybe the re-basecalled files with the newest version of Guppy (v2.1.3) are available if not the raw ones? (i.e. the fastq files - basecalled with the newest version of Guppy (v 2.1.3)?)

Thank you,
Eleni

**Comment by mitenjain** [comment]
Hello @eleniadam ,

They should be available. I will look them up with help from @nickloman and @mattloose and get back to you.

-Miten

**Comment by eleniadam** [comment]
Hi @mitenjain , @nickloman & @mattloose ,

Have you maybe been able to locate the files?

Thank you for your time,
Eleni

**Comment by mattloose** [comment]
Yeah - these will be available shortly - they are on the site we just need to link them in.

**Comment by lakhujanivijay** [comment]
Hi @mattloose and @eleniadam,

Any update on this one? I am trying to do variant calling using [`nanopolish index`](https://nanopolish.readthedocs.io/en/latest/manual.html#id2) which requires `fast5` files. Please help.
