### ISSUE TITLE
unable to d/l fastq with '*'

### ISSUE THREAD

**Issue by brentp** [nanopore-wgs-consortium/NA12878#6]
We can't download:
http://s3.amazonaws.com/nanopore-human-wgs/rel3-nanopore-wgs-285174896-FAB45321*.fastq.gz
listed in the FASTQ link in readme
removing the '*' works.

**Comment by mattloose** [comment]
I thought I could edit this direct - but I can't - proposed a fix - hopefully Nick will resolve.
