### ISSUE TITLE
Looking for fast5 files for rel5 

### ISSUE THREAD

**Issue by lakhujanivijay** [nanopore-wgs-consortium/NA12878#60]
Hello @mitenjain ,

I am looking for the  `.FAST5` files (raw) of [`rel5`](https://s3.amazonaws.com/nanopore-human-wgs/rel5-guppy-0.3.0-chunk10k.fastq.gz) of the [NA12878](https://github.com/nanopore-wgs-consortium/NA12878/blob/master/Genome.md) cell line and possibly the `sequencing summary` (`.txt`) file from guppy. But I have been unable to locate them. Are they available somewhere else?

**Comment by mitenjain** [comment]
Hello and sorry for the delay. 

We will try to sort this out in a couple of days.

**Comment by mattloose** [comment]
The sequencing summary files are not available. We are planning an update to rel6 shortly which will include the latest basecaller types. All of the fast5s for the rel5 release are available on the ENA for download. This will be your best place to get the raw fast5 files right now.

**Comment by lakhujanivijay** [comment]
Can you please do us a favour by sharing the ENA link ? I am sure there are many of us looking for this. I highly appreciate your quick response. :+1:

**Comment by mattloose** [comment]
https://www.ebi.ac.uk/ena/data/view/PRJEB23027

Here you go!

**Comment by lakhujanivijay** [comment]
That is really helpful. Thank you so much :+1:

**Comment by lakhujanivijay** [comment]
Just wanted to add that without the `sequencing_summary.txt` file, the indexing step using nanopolish is too slow. See below link:

http://simpsonlab.github.io/2018/02/16/nanopolish-v0.9.0/
