### ISSUE TITLE
Date of sequencing, Guppy version and parameters for the rel5 Guppy 0.3 gDNA dataset (10kb chunk size)?

### ISSUE THREAD

**Issue by pjedge** [nanopore-wgs-consortium/NA12878#65]
Could you please share the date of sequencing, the version of Guppy, and the parameters used for Guppy on the rel5 genomic DNA dataset?

**Comment by mattloose** [comment]
The dates of sequencing are as the original rel3 and rel4 data - so no new sequencing was carried out for rel5. The basecaller and parameters are described here - https://github.com/nanopore-wgs-consortium/NA12878/blob/master/nanopore-human-genome/rel5.md

We will be releasing a further update in the next couple of weeks which has been called with the latest flip flop callers.
