### ISSUE TITLE
Fast5 folders misnamed and not compressed?

### ISSUE THREAD

**Issue by Shians** [nanopore-wgs-consortium/NA12878#66]
I downloaded [rel3-fast5-chr17.part06.tar](http://s3.amazonaws.com/nanopore-human-wgs/rel3-fast5-chr17.part06.tar) from https://github.com/nanopore-wgs-consortium/NA12878/blob/master/nanopore-human-genome/rel_3_4.md. When running `tar -xf rel3-fast5-chr17.part06.tar` I end up with the directory `rel3/${chr}/${fn}/(fast5 files here)` where `${chr}` and `${fn}` are the actual names of the folders, looks like some string interpolation went wrong somewhere.

Also is there a reason none of these tar archives are gzipped?

**Comment by mattloose** [comment]
Hi - yes you've spotted an error in the folder naming. We are in the process of repacking all these files into multi fast5 files and will be re-releasing them such that this issue should be resolved. Look for rel6 in the next couple of weeks. If you want the multi files sooner we might be able to sort that out.

With respect to the non-gzipping of the tar archives, we found at the time that you didn't get a significant extra saving on gzipping these archives. However, the fast5s in rel3 are significantly out of date with the current multi-format - hence the fact that we are repackaging them now.

Hope this helps.
