### ISSUE TITLE
When will the flip-flop called data be available for the gDNA?

### ISSUE THREAD

**Issue by oneillkza** [nanopore-wgs-consortium/NA12878#67]
I saw that in #65, @mattloose mentioned that a new release would be available, basecalled with the new high-accuracy flip-flop method. That post mentioned it being "in the next couple of weeks", but was about five weeks ago. Has there been any news on this?

Alternately, would it be possible to download the fast5 in the newer, more compact format? The fast5 I see some links to download those, but they seem to be about 30-40TB for 30X, which is not really feasible for me to download right now. More current fast5 should be 1/20th that size, and would be easy to basecall myself.

Thanks for making this data available!

**Comment by mattloose** [comment]
Hi - sorry about the delays. The Multi files are around 2.3T and will be available shortly as will the basecalls. I am just investigating the option of introducing the newer ONT compressed format for the Multis. 
I'll try and get the interim release up in the next few days.
Cheers
Matt

**Comment by oneillkza** [comment]
Thanks so much @mattloose ! I'm excited about the new compressed format too!

**Comment by mattloose** [comment]
Just to say data are available now but the compressed format isn't yet. The multifast5 files are now only 4.5 Tb in size.
