### ISSUE TITLE
Questions about rel3 fastq files of genomic DNA project

### ISSUE THREAD

**Issue by ttbond** [nanopore-wgs-consortium/NA12878#69]
Hi~
I have a question about the fastq files of rel3. As far as I know,  after the nanopore minion sequencing, the fastq files and fast5 files will be classified into two directiories including "pass" and "fail" by metrichor based on the quality of the reads. So my question is the fastq files (and also the fast5 files) publiced here only contain the files in pass directory or the files in both pass and fail directories.

**Comment by mattloose** [comment]
Rel3 contains all fastq - so pass and fail. The pass fail divide is a simple quality split. 

Please note that the rel3 data really shouldn’t be used for evaluating Nanopore performance now.

**Comment by ttbond** [comment]
Thank you for your reply.
