### ISSUE TITLE
Is the raw data(signal data) of rel6 the same as rel3, rel4?

### ISSUE THREAD

**Issue by huangnengCSU** [nanopore-wgs-consortium/NA12878#70]
Hi:
    Is the difference between rel6 and rel3,rel4 the basecalling tool and the file storage format? Are the original sequencing signals of rel6 and rel3,rel4 the same?

**Comment by mattloose** [comment]
The raw signal file data are the same yes. As you say it is the basecaller and the file storage format that have changed only.
