### ISSUE TITLE
FAST5 Directory Names

### ISSUE THREAD

**Issue by marcus1487** [nanopore-wgs-consortium/NA12878#8]
I have started to download some of the FAST5 tarballs and there appears to be an issue with the directory structure within each of the tarballs. Each of the tarballs I have untar'ed thus far creates the following directory structure "./rel3/${chr}/${fn}" (literal file name; those are not placeholder curly brackets). This is not a huge deal, but it does involve unzipping the files within separate directories to avoid incredibly large numbers of files within the directory containing all FAST5 files. I know this is a lot of work to re-upload, but thought it worth mentioning.

**Comment by nickloman** [comment]
Thanks, we did realise this but it takes so long to upload the data we'll likely not fix it until the next release!
