### ISSUE TITLE
Summary file for cDNA data

### ISSUE THREAD

**Issue by vkkodali** [nanopore-wgs-consortium/NA12878#84]
Could you please check the [Summary file for the cDNA data](http://s3.amazonaws.com/nanopore-human-wgs/rna/summaries/NA12878-cDNA_All_Guppy_3.2.6_sequencing_summary.txt.gz)? It appears that the first set of lines are in binary.

**Comment by mitenjain** [comment]
We are checking now and will update the file as needed shortly. 

-Miten

**Comment by mitenjain** [comment]
This issue should be fixed now. Thank you for bringing this to our attention. 

Cheers,
Miten

**Comment by vkkodali** [comment]
Thank you @mitenjain
