### ISSUE TITLE
number of reads in summary and fastq files do not match

### ISSUE THREAD

**Issue by vkkodali** [nanopore-wgs-consortium/NA12878#88]
Aren't the number of reads in the summary and fastq files expected to be the same? 
```
$ zgrep -v '^filename' NA12878-cDNA_All_Guppy_3.2.6_sequencing_summary.txt.gz | cut -f1,2 | sort -u | wc -l
21229110

$ zcat NA12878-cDNA_All_Guppy_3.2.6.fastq.gz | paste - - - - | wc -l
24531552
```

**Comment by mitenjain** [comment]
They should match. I'll look into this and get back here in a couple of days.

**Comment by mitenjain** [comment]
Hello, 

We have now updated the data and fixed the issues in rel2. The new basecalls are with Guppy 4.2.2. Hope this helps. 

Let us know if you have any questions.
