### ISSUE TITLE
Where is CHR22?

### ISSUE THREAD

**Issue by drdivine** [nanopore-wgs-consortium/NA12878#98]
Dear Maintainers of this awesome repository,

I can't find chr22 in the fast5 table. Is this a mistake, or was it purposely omitted?

I'm trying to validate my methylation pipeline which starts with base-calling. I wanted a small chromosome to test. Any tips would be greatly appreciated.

Best Regards

Matt

**Comment by mattloose** [comment]
Ha - well - that's an omission! Have you tried looking for the file by using chr22 in the file name instead of chr21? I will have a look and try and fix ASAP for you when I get a moment!

**Comment by mattloose** [comment]
F

**Comment by mattloose** [comment]
Now fixed. Note - chr22 is 4 Mb longer than chr21 so - if you want the shortest chromosome to test go with 21. Probably why the absence of 22 hadn't been noticed for so long.
